
language: node_js
node_js:
  - "8"

cache:
   directories:
      - node_modules
      - $HOME/.meteor/

before_install:
   - curl https://install.meteor.com | /bin/sh
before_script:
  - npm install
script: 
  - meteor run

sudo: required
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
- g++-4.8
